# Настройки микросервиса подписания CMS

server:
  port: 8080

# Путь к сертификату (для включения в CMS)
cert_path: "etc/cert.crt"

# Имя провайдера CSP (по умолчанию Avest CSP Bel Pro)
provider_name: "Avest CSP Bel Pro"

# Список личных ключей / контейнеров с паролями
keys:
  - key_id: "Zysko_22_01_26_20_23"
    pin: "Ee17011985"
  # - key_id: "AnotherKey"
  #   pin: "secret"
